import { eq } from 'drizzle-orm';
import { sources } from '../db/schema';
import type { Database } from '../db/connection';

export interface Source {
	id: string;
	seedId: string;
	topicId: string;
	title: string;
	type: string;
	originalUrl: string | null;
	originalFormat: string | null;
	content: string | null;
	rawPath: string | null;
	provenance: string | null;
	metadata: string | null;
	createdAt: string;
}

export interface CreateSourceInput {
	id: string; // pre-generated by caller so file storage paths stay consistent
	seedId: string;
	topicId: string;
	title: string;
	type: string;
	content: string;
	originalFormat: string;
	originalUrl?: string;
	rawPath?: string;
	provenance?: string;
	metadata?: Record<string, unknown>;
}

export async function createSource(db: Database, input: CreateSourceInput): Promise<Source> {
	const record: Source = {
		id: input.id,
		seedId: input.seedId,
		topicId: input.topicId,
		title: input.title,
		type: input.type,
		content: input.content,
		originalUrl: input.originalUrl ?? null,
		originalFormat: input.originalFormat,
		rawPath: input.rawPath ?? null,
		provenance: input.provenance ?? null,
		metadata: input.metadata ? JSON.stringify(input.metadata) : null,
		createdAt: new Date().toISOString()
	};
	await db.insert(sources).values(record);
	return record;
}

export async function getSource(db: Database, id: string): Promise<Source | null> {
	const results = await db.select().from(sources).where(eq(sources.id, id));
	return (results[0] as Source | undefined) ?? null;
}

export async function listSourcesByTopic(db: Database, topicId: string): Promise<Source[]> {
	return db.select().from(sources).where(eq(sources.topicId, topicId)) as Promise<Source[]>;
}

export async function listSourcesBySeed(db: Database, seedId: string): Promise<Source[]> {
	return db.select().from(sources).where(eq(sources.seedId, seedId)) as Promise<Source[]>;
}
